# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               HMKCODE
tagline:             'Code First!'
description:         'A reserved <a href="http://hmkcode.com" target="_blank">hmkcode</a> Made by <a href="https://twitter.com/hmkcode" target="_blank">@hmkcode</a>.'
url:                 http://hmkcode.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Hani M. K.
  url:               https://twitter.com/hmkcode

# Custom vars
version:             1.0.0


gems: [jekyll-paginate]